// <auto-generated />
using System;
using CleanArchitecture.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240618190300_NovaTabela-TbPROD")]
    partial class NovaTabelaTbPROD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CleanArchitecture.Domain.Produtos.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PROD_Id");

                    b.Property<string>("Cor")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PROD_Cor");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("PROD_CreatedOn");

                    b.Property<string>("Descrição")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("PROD_Descrição");

                    b.Property<ulong>("Garantia")
                        .HasColumnType("bit")
                        .HasColumnName("PROD_Garantia");

                    b.Property<string>("Marca")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PROD_Marca");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("PROD_Nome");

                    b.Property<int>("RegDel")
                        .HasColumnType("int")
                        .HasColumnName("PROD_RegDel");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("PROD_UpdatedOn");

                    b.HasKey("Id")
                        .HasName("PROD_01");

                    b.ToTable("tbPROD", (string)null);
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("USUA_Id");

                    b.Property<ulong>("Admin")
                        .HasColumnType("bit")
                        .HasColumnName("USUA_Admin");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("USUA_CreatedOn");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("USUA_Email");

                    b.Property<int>("Idade")
                        .HasColumnType("int")
                        .HasColumnName("USUA_Idade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("USUA_Nome");

                    b.Property<Guid>("RegDel")
                        .HasColumnType("char(36)")
                        .HasColumnName("RegDel");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("USUA_Senha");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("USUA_UpdatedOn");

                    b.HasKey("Id")
                        .HasName("USUA_01");

                    b.ToTable("tbUSUA", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
